import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next fullstack',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-[1336px] min-h-[00vh] px-[60px] mx-auto flex flex-col justify-between'>
        <Navbar/>
        {children}
        <Footer/> 
        </div>
      </body>
    </html>
  )
}
